name: Push to AWS CodeCommit

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Configure Git to use AWS credential helper
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true

      - name: Add AWS remote & Push
        run: |
          git remote add aws https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/yantra-app
          git push aws HEAD:${GITHUB_REF_NAME}
